<?php
// wakka.config.php сохранен Sat May 13 19:28:20 2006
// не меняйте wakka_version вручную!

$wakkaConfig = array(
	"mysql_host" => "mysql",
	"mysql_database" => "av_wakka",
	"mysql_user" => "av_wakka",
	"table_prefix" => "wakka_",
	"cookie_prefix" => "wakka_",
	"root_page" => "HomePage",
	"wakka_name" => "Мир Авангарда",
	"base_url" => "http://avanguard.halogen.kharkov.ua/wacko/",
	"rewrite_mode" => "1",
	"action_path" => "actions",
	"handler_path" => "handlers",
	"language" => "ru",
	"theme" => "tabs",
	"header_action" => "header",
	"footer_action" => "footer",
	"show_datetime" => "Y",
	"show_spaces" => "Y",
	"default_typografica" => "1",
	"default_showdatetime" => "1",
	"paragrafica" => "1",
	"referrers_purge_time" => "1",
	"pages_purge_time" => "0",
	"hide_comments" => "0",
	"debug" => "0",
	"youarehere_text" => "",
	"hide_locked" => "1",
	"allow_rawhtml" => "1",
	"disable_safehtml" => "0",
	"urls_underscores" => "0",
	"allrecentchanges_page" => "",
	"allpageindex_page" => "",
	"default_write_acl" => "*",
	"default_read_acl" => "*",
	"default_comment_acl" => "*",
	"default_rename_redirect" => "1",
	"owners_can_remove_comments" => "1",
	"allow_registration" => "1",
	"standart_handlers" => "acls|addcomment|claim|diff|edit|msword|print|referrers|referrers_sites|remove|rename|revisions|revisions\.xml|show|watch|settings",
	"edit_table_based" => "0",
	"revisions_hide_cancel" => "0",
	"footer_comments" => "1",
	"footer_files" => "1",
	"disable_tikilinks" => "0",
	"remove_onlyadmins" => "0",
	"upload" => "admins",
	"upload_images_only" => "0",
	"upload_max_size" => "190",
	"upload_max_per_user" => "100",
	"upload_path" => "files",
	"upload_path_per_page" => "files/perpage",
	"upload_banned_exts" => "php|cgi|js|php|php3|php4|php5|pl|ssi|jsp|phtm|phtml|shtm|shtml|xhtm|xht|asp|aspx|htw|ida|idq|cer|cdx|asa|htr|idc|stm|printer|asax|ascx|ashx|asmx|axd|vdisco|rem|soap|config|cs|csproj|vb|vbproj|webinfo|licx|resx|resources",
	"outlook_workaround" => "1",
	"disable_autosubscribe" => "0",
	"allow_gethostbyaddr" => "1",
	"multilanguage" => "1",
	"cache" => "0",
	"cache_dir" => "_cache/",
	"cache_ttl" => "600",
	"db_collation" => "cp1251",
	"rename_globalacl" => "Admins",
	"mysql_password" => "ahw1eiXe",
	"admin_name" => "AvanguarD",
	"admin_email" => "nowhere_sp@ukr.net",
	"wakka_version" => "0.1.2",
	"wacko_version" => "R4.2",
);
$wakkaConfig["aliases"] = array(
	"Admins" => "AlexYegupov",
);

?>